### ISSUE TITLE
make search path generic

### ISSUE THREAD

**Issue by mbdraks** [rolando-anton/fpoc-inside-playbooks#1]
https://github.com/rolando-anton/forti-attack_range/blob/86b9b6c5ab0f948286acfa805bcea37c38f71c14/ansible/roles/domain-controller/tasks/populate_users.yml#L4

Could be improved using this:

```yaml
path: '{{ role_path }}/files/users.csv'
```

**Comment by rolando-anton** [comment]
FIxed, thanks!
